-- Bulk Insert Fireplaces for Tops Fireplaces
-- This script inserts all fireplaces into the Supabase database
-- Run this in Supabase SQL Editor
-- NOTE: Prices are estimated - update with actual prices after running
-- Images can be added manually via admin panel after insertion

INSERT INTO products (
  name,
  description,
  long_description,
  price,
  original_price,
  category,
  subcategory,
  material,
  fuel_type,
  dimensions,
  weight,
  features,
  specifications,
  images,
  badge,
  stock_count,
  in_stock,
  featured,
  status
) VALUES

-- PROFLAME SERIES
(
  'Proflame 1000',
  'Panoramic electric fireplace with lifelike flame visuals and modern controls.',
  'The Proflame 1000 combines panoramic glass design, natural oak logs, and efficient LED flame effects. With app and remote control, variable heat output, and flame-only operation, it''s ideal for creating a luxury focal point in any media wall.',
  1299.00,
  NULL,
  'electric',
  'fireplace',
  'Steel & Glass',
  'electric',
  'Width: 1000 mm',
  NULL,
  ARRAY['Realistic oak log fuel bed', 'Flame-only mode', 'Smart control via app/remote', 'Energy-efficient LEDs', 'Wall-mounted or media-wall installation', 'Multi-sided glass: 1-, 2-, or 3-sided install'],
  '{"Heat Output": "0.9 kW / 1.8 kW", "Width": "1000 mm", "Installation": "Multi-sided (1-, 2-, or 3-sided)", "Control": "Remote & App"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

(
  'Proflame 1250',
  'Wide-format electric fire for striking modern interiors.',
  'The Proflame 1250 delivers a broader flame picture with realistic fuel effects and rich LED ambience. Its versatile multi-sided design and smart control options make it perfect for large feature walls.',
  1399.00,
  NULL,
  'electric',
  'fireplace',
  'Steel & Glass',
  'electric',
  'Width: 1250 mm',
  NULL,
  ARRAY['Extra-wide flame display', 'Adjustable flame brightness', 'Smart remote/app control', 'Flame-only mode', 'Oak log bed', 'Multi-sided design'],
  '{"Heat Output": "1.0-1.8 kW", "Width": "1250 mm", "Installation": "Multi-sided"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

(
  'Proflame 1600',
  'Ultra-wide electric fire with panoramic flame view.',
  'The Proflame 1600 is built for luxury media walls, offering an extra-wide flame view and vibrant LED effects. Adjustable heating, app control, and multi-sided design make it a show-stopping centrepiece.',
  1699.00,
  NULL,
  'electric',
  'fireplace',
  'Steel & Glass',
  'electric',
  'Width: 1600 mm',
  NULL,
  ARRAY['Extra-large viewing window', 'LED flame lighting', 'Flame-only option', 'Smart remote/app control', 'Flexible installation (1-3 sides)'],
  '{"Heat Output": "1.8 kW", "Width": "1600 mm", "Installation": "Multi-sided"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  true,
  'active'
),

(
  'Proflame Asencio Noir',
  'Elegant black electric fireplace for stylish interiors.',
  'The Asencio Noir combines a deep black finish with vivid LED flames for dramatic visual impact. With efficient heating and mood lighting control, it enhances modern living spaces effortlessly.',
  1299.00,
  NULL,
  'electric',
  'fireplace',
  'Black Steel & Glass',
  'electric',
  'Width: ~1000 mm',
  NULL,
  ARRAY['Sleek black frame', 'Realistic flame bed', 'LED mood lighting', 'Remote control', 'Flame-only option'],
  '{"Heat Output": "1.8 kW", "Width": "~1000 mm", "Finish": "Deep black Noir"}',
  ARRAY[]::TEXT[],
  'New',
  0,
  false,
  false,
  'active'
),

(
  'Proflame Celena Noir',
  'Compact electric fire in elegant black.',
  'The Celena Noir delivers bold black styling in a compact form. With adjustable heat, vivid LED flames, and smart control, it''s perfect for smaller rooms or minimalist feature walls.',
  1199.00,
  NULL,
  'electric',
  'fireplace',
  'Black Steel & Glass',
  'electric',
  'Width: 1000 mm',
  NULL,
  ARRAY['Compact design', 'LED flame realism', 'Smart control', 'Flame-only mode', 'Minimal black trim'],
  '{"Heat Output": "1.0 kW / 2.0 kW", "Width": "1000 mm"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

(
  'Proflame SL Adonis',
  'Slim electric fire ideal for compact media walls.',
  'The Proflame SL Adonis brings powerful heating and realistic flames in a space-saving design. It''s perfect for shallow wall recesses or apartments, offering both warmth and visual elegance.',
  1249.00,
  NULL,
  'electric',
  'fireplace',
  'Steel & Glass',
  'electric',
  'Slimline depth: ~150 mm',
  NULL,
  ARRAY['Slimline profile', 'LED flame bed', 'App/remote control', 'Energy-saving design', 'Multiple install configurations'],
  '{"Heat Output": "1.0-1.8 kW", "Depth": "~150 mm", "Profile": "Slimline"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

(
  'Proflame Monroe 1250/1000 Suite',
  'Complete limestone fireplace suite with built-in electric fire.',
  'The Proflame Monroe Suite blends natural limestone craftsmanship with modern electric fire technology. Offering vivid flame visuals, quick installation, and efficient heating, it''s a timeless yet contemporary statement piece.',
  2499.00,
  NULL,
  'limestone',
  'suite',
  'Natural Limestone & Steel',
  'electric',
  'Sizes: 1000 mm / 1250 mm',
  NULL,
  ARRAY['Natural limestone surround', 'Integrated electric fire', 'LED flame visuals', 'Simple installation', 'Flame-only function', 'Fully assembled suite'],
  '{"Heat Output": "1.8 kW", "Sizes Available": "1000 mm / 1250 mm", "Type": "Complete Suite"}',
  ARRAY[]::TEXT[],
  'Premium',
  0,
  false,
  true,
  'active'
),

-- CELSI DLX SERIES
(
  'Celsi DLX 2000',
  'Premium wall-mounted electric fireplace with smart control and vivid customisable flames.',
  'The Celsi DLX series delivers ultra-realistic flame visuals through advanced LED projection. Smart app and voice control, full colour customisation, and flexible installation make it perfect for modern interiors. With up to 2 kW heat output and stunning visuals, it''s the definition of luxury electric heating.',
  2199.00,
  NULL,
  'electric',
  'fireplace',
  'Steel & Tempered Glass',
  'electric',
  'Width: 2000 mm',
  NULL,
  ARRAY['Multi Flame Projection®', 'Living Ember Bed®', '16 preset flame colours + 100 custom tones', 'Realistic ceramic logs', 'Ambient backlighting', 'Programmable timer & thermostat', 'Voice & app control (Alexa, Google)', 'Multi-sided install options'],
  '{"Heat Output": "1.0-2.0 kW", "Width": "2000 mm", "Control": "Voice & App (Alexa, Google, iOS, Android)", "Installation": "Multi-sided (1-, 2-, 3-sided)", "Flame Colours": "16 presets + 100 custom"}',
  ARRAY[]::TEXT[],
  'Premium',
  0,
  false,
  true,
  'active'
),

(
  'Celsi DLX 1800',
  'Premium wall-mounted electric fireplace with smart control and vivid customisable flames.',
  'The Celsi DLX series delivers ultra-realistic flame visuals through advanced LED projection. Smart app and voice control, full colour customisation, and flexible installation make it perfect for modern interiors. With up to 2 kW heat output and stunning visuals, it''s the definition of luxury electric heating.',
  1999.00,
  NULL,
  'electric',
  'fireplace',
  'Steel & Tempered Glass',
  'electric',
  'Width: 1800 mm',
  NULL,
  ARRAY['Multi Flame Projection®', 'Living Ember Bed®', '16 preset flame colours + 100 custom tones', 'Realistic ceramic logs', 'Ambient backlighting', 'Programmable timer & thermostat', 'Voice & app control (Alexa, Google)', 'Multi-sided install options'],
  '{"Heat Output": "1.0-2.0 kW", "Width": "1800 mm", "Control": "Voice & App (Alexa, Google, iOS, Android)", "Installation": "Multi-sided (1-, 2-, 3-sided)", "Flame Colours": "16 presets + 100 custom"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

(
  'Celsi DLX 1600',
  'Premium wall-mounted electric fireplace with smart control and vivid customisable flames.',
  'The Celsi DLX series delivers ultra-realistic flame visuals through advanced LED projection. Smart app and voice control, full colour customisation, and flexible installation make it perfect for modern interiors. With up to 2 kW heat output and stunning visuals, it''s the definition of luxury electric heating.',
  1799.00,
  NULL,
  'electric',
  'fireplace',
  'Steel & Tempered Glass',
  'electric',
  'Width: 1600 mm',
  NULL,
  ARRAY['Multi Flame Projection®', 'Living Ember Bed®', '16 preset flame colours + 100 custom tones', 'Realistic ceramic logs', 'Ambient backlighting', 'Programmable timer & thermostat', 'Voice & app control (Alexa, Google)', 'Multi-sided install options'],
  '{"Heat Output": "1.0-2.0 kW", "Width": "1600 mm", "Control": "Voice & App (Alexa, Google, iOS, Android)", "Installation": "Multi-sided (1-, 2-, 3-sided)", "Flame Colours": "16 presets + 100 custom"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

(
  'Celsi DLX 1250',
  'Premium wall-mounted electric fireplace with smart control and vivid customisable flames.',
  'The Celsi DLX series delivers ultra-realistic flame visuals through advanced LED projection. Smart app and voice control, full colour customisation, and flexible installation make it perfect for modern interiors. With up to 2 kW heat output and stunning visuals, it''s the definition of luxury electric heating.',
  1599.00,
  NULL,
  'electric',
  'fireplace',
  'Steel & Tempered Glass',
  'electric',
  'Width: 1250 mm',
  NULL,
  ARRAY['Multi Flame Projection®', 'Living Ember Bed®', '16 preset flame colours + 100 custom tones', 'Realistic ceramic logs', 'Ambient backlighting', 'Programmable timer & thermostat', 'Voice & app control (Alexa, Google)', 'Multi-sided install options'],
  '{"Heat Output": "1.0-2.0 kW", "Width": "1250 mm", "Control": "Voice & App (Alexa, Google, iOS, Android)", "Installation": "Multi-sided (1-, 2-, 3-sided)", "Flame Colours": "16 presets + 100 custom"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

(
  'Celsi DLX 1000',
  'Premium wall-mounted electric fireplace with smart control and vivid customisable flames.',
  'The Celsi DLX series delivers ultra-realistic flame visuals through advanced LED projection. Smart app and voice control, full colour customisation, and flexible installation make it perfect for modern interiors. With up to 2 kW heat output and stunning visuals, it''s the definition of luxury electric heating.',
  1399.00,
  NULL,
  'electric',
  'fireplace',
  'Steel & Tempered Glass',
  'electric',
  'Width: 1000 mm',
  NULL,
  ARRAY['Multi Flame Projection®', 'Living Ember Bed®', '16 preset flame colours + 100 custom tones', 'Realistic ceramic logs', 'Ambient backlighting', 'Programmable timer & thermostat', 'Voice & app control (Alexa, Google)', 'Multi-sided install options'],
  '{"Heat Output": "1.0-2.0 kW", "Width": "1000 mm", "Control": "Voice & App (Alexa, Google, iOS, Android)", "Installation": "Multi-sided (1-, 2-, 3-sided)", "Flame Colours": "16 presets + 100 custom"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

(
  'Celsi DLX 750',
  'Premium wall-mounted electric fireplace with smart control and vivid customisable flames.',
  'The Celsi DLX series delivers ultra-realistic flame visuals through advanced LED projection. Smart app and voice control, full colour customisation, and flexible installation make it perfect for modern interiors. With up to 2 kW heat output and stunning visuals, it''s the definition of luxury electric heating.',
  1199.00,
  NULL,
  'electric',
  'fireplace',
  'Steel & Tempered Glass',
  'electric',
  'Width: 750 mm',
  NULL,
  ARRAY['Multi Flame Projection®', 'Living Ember Bed®', '16 preset flame colours + 100 custom tones', 'Realistic ceramic logs', 'Ambient backlighting', 'Programmable timer & thermostat', 'Voice & app control (Alexa, Google)', 'Multi-sided install options'],
  '{"Heat Output": "1.0-2.0 kW", "Width": "750 mm", "Control": "Voice & App (Alexa, Google, iOS, Android)", "Installation": "Multi-sided (1-, 2-, 3-sided)", "Flame Colours": "16 presets + 100 custom"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

(
  'Celsi DLX 600',
  'Premium wall-mounted electric fireplace with smart control and vivid customisable flames.',
  'The Celsi DLX series delivers ultra-realistic flame visuals through advanced LED projection. Smart app and voice control, full colour customisation, and flexible installation make it perfect for modern interiors. With up to 2 kW heat output and stunning visuals, it''s the definition of luxury electric heating.',
  1099.00,
  NULL,
  'electric',
  'fireplace',
  'Steel & Tempered Glass',
  'electric',
  'Width: 600 mm',
  NULL,
  ARRAY['Multi Flame Projection®', 'Living Ember Bed®', '16 preset flame colours + 100 custom tones', 'Realistic ceramic logs', 'Ambient backlighting', 'Programmable timer & thermostat', 'Voice & app control (Alexa, Google)', 'Multi-sided install options'],
  '{"Heat Output": "1.0-2.0 kW", "Width": "600 mm", "Control": "Voice & App (Alexa, Google, iOS, Android)", "Installation": "Multi-sided (1-, 2-, 3-sided)", "Flame Colours": "16 presets + 100 custom"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

(
  'Celsi DLX Navarro 600T Suite',
  'Compact electric suite for easy installation and instant ambience.',
  'The Celsi Navarro 600T Suite offers plug-and-play luxury with vivid LED flames, adjustable colour settings, and no recess requirement. Ideal for smaller rooms, apartments, or as a ready-to-go wall feature.',
  1499.00,
  NULL,
  'electric',
  'suite',
  'Painted MDF & Glass',
  'electric',
  'Width: 600 mm',
  NULL,
  ARRAY['Integrated surround suite', 'Realistic flame visuals', 'Remote & app control', 'Flame-only setting', 'Simple installation (no recess needed)', 'Plug-and-play setup'],
  '{"Heat Output": "1.5 kW", "Width": "600 mm", "Installation": "Plug-and-play, no recess required"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

-- OER / FIRETTI STOVES
(
  'OER/Firetti Milan Electric Stove',
  'Traditional electric stove combining classic looks with modern tech.',
  'The Milan Electric Stove captures the charm of a log burner without the mess. Plug-and-play simplicity, flame-only operation, and lifelike LED flames make it ideal for both contemporary and rustic homes.',
  799.00,
  NULL,
  'electric',
  'stove',
  'Cast Iron-effect Steel',
  'electric',
  'H 600 × W 480 × D 320 mm',
  NULL,
  ARRAY['Realistic LED flame effect', 'Flame-only mode', 'Remote control', 'No flue required', 'Customisable fuel bed', 'Freestanding design'],
  '{"Heat Output": "up to 1.9 kW", "Dimensions": "H 600 × W 480 × D 320 mm", "Design": "Freestanding"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

(
  'OER/Firetti Naples Electric Stove',
  'Elegant freestanding stove for cosy electric warmth.',
  'The Naples Electric Stove provides the atmosphere of a wood-burning stove with the convenience of electric power. Remote control, flame-only ambience, and efficient heating bring charm and comfort to any room.',
  849.00,
  NULL,
  'electric',
  'stove',
  'Cast Iron-effect Steel',
  'electric',
  'Freestanding',
  NULL,
  ARRAY['Realistic flame display', 'Adjustable thermostat', 'Flame-only setting', 'Remote control', 'Easy installation', 'Freestanding'],
  '{"Heat Output": "up to 1.9 kW", "Design": "Freestanding"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

-- DIMPLEX SERIES
(
  'Dimplex Dumfries',
  'Stone-effect electric suite with lifelike flame depth and warmth.',
  'The Dumfries suite blends traditional mantel styling with Dimplex''s Optiflame 3D technology. Enjoy vivid flame depth, adjustable fuel beds, and up to 2 kW heat for year-round ambience and comfort.',
  899.00,
  NULL,
  'electric',
  'suite',
  'Stone-effect & Glass',
  'electric',
  'H 613 × W 517 × D 202 mm',
  NULL,
  ARRAY['3D LED flame visuals', 'Multiple fuel bed options (logs/crystals/pebbles)', 'Flame-only mode', 'Remote control', '2-year warranty'],
  '{"Heat Output": "2 kW", "Dimensions": "H 613 × W 517 × D 202 mm", "Flame Technology": "Optiflame 3D", "Warranty": "2 years"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

(
  'Dimplex Lerwick',
  'Modern stone-effect electric suite with 3D flame visuals.',
  'The Dimplex Lerwick offers homely warmth with natural stone textures and realistic flame visuals. Its Optiflame 3D system adds depth and movement, creating a cosy centrepiece for any room.',
  949.00,
  NULL,
  'electric',
  'suite',
  'Stone-effect',
  'electric',
  NULL,
  NULL,
  ARRAY['LED flame realism', 'Remote control', 'Flame-only function', 'Rustic stone finish', 'Plug-in installation'],
  '{"Heat Output": "2 kW", "Flame Technology": "Optiflame 3D"}',
  ARRAY[]::TEXT[],
  NULL,
  0,
  false,
  false,
  'active'
),

(
  'Dimplex Artesia',
  'Modern wall-mounted electric fire with vibrant LED effects.',
  'The Dimplex Artesia brings contemporary style with a glossy black glass finish and customisable flame colours. Its slim profile, remote control, and flame-only operation make it a striking feature in modern interiors.',
  1099.00,
  NULL,
  'electric',
  'fireplace',
  'Black Glass',
  'electric',
  'Wall-mounted design',
  NULL,
  ARRAY['Sleek black glass fascia', 'Colour-changing flame', 'Remote control', 'Wall-mountable', 'Flame-only setting'],
  '{"Heat Output": "1.0-2.0 kW", "Design": "Wall-mounted"}',
  ARRAY[]::TEXT[],
  'New',
  0,
  false,
  false,
  'active'
);

-- IMPORTANT NOTES:
-- 1. Prices are estimated - please update with actual prices after running this script
-- 2. Images are empty arrays - add them manually via the admin panel after products are created
-- 3. All products are set to in_stock: false initially - update when stock arrives
-- 4. Featured products: Proflame 1600, Proflame Monroe Suite, Celsi DLX 2000
-- 5. Update stock_count and in_stock when you have inventory information

